version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/node'
        versions:
          - '<22'
          - '>=23'
    groups:
      typescript:
        patterns:
          - 'typescript'
          - 'ts-*'
          - '@types/*'
      dev-tooling:
        dependency-type: 'development'
        patterns:
          - 'eslint*'
          - 'prettier'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'globals'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
